# Generated by Django 4.0.4 on 2022-05-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('edit_time', models.DateTimeField(auto_now=True)),
                ('click_cnt', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
            ],
            options={
                'ordering': ['upload_time'],
            },
        ),
    ]
