# Generated by Django 4.0.4 on 2022-05-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-upload_time']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='edit_time',
        ),
    ]
