# Generated by Django 4.0.4 on 2022-05-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prof', models.CharField(max_length=30, null=True)),
                ('memo', models.TextField(max_length=100)),
                ('belong_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sugangApp.major')),
            ],
        ),
    ]
