# Generated by Django 4.0.4 on 2022-05-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugangApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='name',
            new_name='major_name',
        ),
    ]
